networks:
  app-network:
    driver: bridge

# Vector database container
services:

  frontend:
    networks:
      - app-network
    container_name: frontend
    build: frontend
    environment:
      BACK: "http://backend:3000"
    ports:
      - "3001:3000"
    expose:
      - "3000"
    depends_on:
      - backend
    restart: always

  backend:
    networks:
      - app-network
    container_name: backend
    build: backend
    environment:
      HOST: "weaviate:8080"
      SCHEME: "http"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - weaviate
    restart: always

  weaviate:
    networks:
      - app-network
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    expose:
      - "8080"
      - "50051"
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      BIND_INFERENCE_API: 'http://multi2vec-bind:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-bind'
      ENABLE_MODULES: 'multi2vec-bind'
      CLUSTER_HOSTNAME: 'node1'

  multi2vec-bind:
    networks:
      - app-network
    image: cr.weaviate.io/semitechnologies/multi2vec-bind:imagebind
    environment:
      ENABLE_CUDA: '0'

volumes:
  weaviate_data:
